### ISSUE TITLE
JBOSS Error

### ISSUE THREAD

**Issue by loretoparisi** [shekhargulati/day20-stanford-sentiment-analysis-demo#3]
2015/05/13 06:51:56,980 INFO  [org.jboss.as.server](ServerService Thread Pool -- 38) JBAS015859: Deployed "ROOT.war" (runtime-name : "ROOT.war")
2015/05/13 06:51:56,984 INFO  [org.jboss.as.controller](Controller Boot Thread) JBAS014774: Service status report
JBAS014777:   Services which failed to start:      service jboss.deployment.unit."ROOT.war".POST_MODULE: org.jboss.msc.service.StartException in service jboss.deployment.unit."ROOT.war".POST_MODULE: JBAS018733: Failed to process phase POST_MODULE of deployment "ROOT.war"
2015/05/13 06:51:57,120 INFO  [org.jboss.as](Controller Boot Thread) JBAS015961: Http management interface listening on http://127.9.197.1:9990/management
2015/05/13 06:51:57,120 INFO  [org.jboss.as](Controller Boot Thread) JBAS015951: Admin console listening on http://127.9.197.1:9990
2015/05/13 06:51:57,120 ERROR [org.jboss.as](Controller Boot Thread) JBAS015875: JBoss EAP 6.4.0.GA (AS 7.5.0.Final-redhat-21) started (with errors) in 21237ms - Started 204 of 323 services (1 services failed or missing dependencies, 144 services are lazy, passive or on-demand)
2015/05/13 06:51:57,277 INFO  [org.jboss.as.server.deployment](MSC service thread 1-7) JBAS015877: Stopped deployment ROOT.war (runtime-name: ROOT.war) in 59ms
2015/05/13 06:51:57,380 INFO  [org.jboss.as.server](DeploymentScanner-threads - 2) JBAS015858: Undeployed "ROOT.war" (runtime-name: "ROOT.war")
2015/05/13 06:51:57,380 INFO  [org.jboss.as.controller](DeploymentScanner-threads - 2) JBAS014774: Service status report
JBAS014777:   Services which failed to start:      service jboss.deployment.unit."ROOT.war".POST_MODULE

**Comment by loretoparisi** [comment]
It turns out that the error was due to Java Version on the OpenShift and this git repo:

2015/05/13 07:03:57,889 WARN  [org.jboss.modules](MSC service thread 1-4) Failed to define class com.sentiments.rest.JaxrsInitializer in Module "deployment.ROOT.war:main" from Service Module Loader: java.lang.UnsupportedClassVersionError: com/sentiments/rest/JaxrsInitializer : Unsupported major.minor version 51.0
    at java.lang.ClassLoader.defineClass1(Native Method) [rt.jar:1.6.0_35]
    at java.lang.ClassLoader.defineClass(ClassLoader.java:643) [rt.jar:1.6.0_35]
